<style type="text/css">

.mp-post-info a.mp-info {
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
}
.mp-post-info a.mp-info:hover {
	text-decoration: none;
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
}

.nav .nav-tabs li.active{
	border-top-color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
}

.about-admin h4.admin-title a{
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
}

.about-admin h4.admin-title a:hover {
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
}
.owl-item a.mp-relate-link {
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
}
.owl-item a.mp-relate-link:focus{
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
	text-decoration: none;
}
.owl-item a.mp-relate-link:hover{
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
	text-decoration: none;
}
ul.nav-tabs li.active{
	border-top-color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
	border-top-style: solid;
}
a.label.label-default.tags-list:hover {
	background: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
	border: 1px solid;
}
a.label.label-default.tags-list:focus{
	background: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
ul.menu-categories a.list-categories:hover {
	text-decoration: none;
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
#mostview a.list-post-tabs:hover {
	text-decoration: none;
	background: #fbfbfb;
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
#mostrecent a.list-post-tabs:hover {
	text-decoration: none;
	background: #fbfbfb;
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
h2.mp-post-title a {
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
h2.mp-post-title a:hover {
	text-decoration: none;
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
h2.mp-post-title a.post-link-title:focus {
	text-decoration: none;
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
.mp-post-meta-info a.mp-read-more {
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
.mp-post-meta-info a.mp-read-more:hover {
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;;
}
.breadcrumbs a:hover {
	text-decoration: none !important;
}
.post-info-wraper h2.mp-post-title{
	margin-top: 0px;
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
	color: <?php if($block->getBlogConfig('general/font_color')) echo $block->getBlogConfig('general/font_color')?> !important;
}
</style>
