<?php
$posts = $block->getMosviewPosts();
$postsRecent = $block->getRecentPost();
?>

<div class="mp-sidebar mpcss row">
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mageplaza_blog_sidebar_above_popular_widget')->toHtml();?>
</div>

<div class="mp-sidebar mpcss">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#mostview"><?php echo __('Popular') ?></a></li>
			<li><a data-toggle="tab" href="#mostrecent"><?php echo __('Recent') ?></a></li>
		</ul>
		
		<div class="tab-content">
			<div id="mostview" class="tab-pane fade in active">
				<?php if ($posts->getSize()): ?>
					<?php foreach ($posts as $post): ?>
						<a class="list-post-tabs" href="<?php echo $block->getUrlByPost($post) ?>">
							<div class="post-left">
								<img class="img-responsive" src="<?php echo $block->getImageUrl($post->getImage())?>">
							</div>
							<div class="post-right">
								<span><?php echo $post->getName() ?></span>
								<span class="create-at">
									<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
									$object = $objectManager->get('\Magento\Framework\Stdlib\DateTime\DateTime');
									$dateFormat = date('Y-m-d',$object->timestamp($post->getCreatedAt()));
									echo $dateFormat;
									?>
								</span>
							</div>
						</a>
					<?php endforeach; ?>
	
				<?php else: ?>
					<?php echo __('<div style="'.'height: 50px;line-height: 50px;text-align: center;'.'">No Posts</div>') ?>
				<?php endif; ?>
			</div>
			<div id="mostrecent" class="tab-pane fade">
				<?php if ($postsRecent->getSize()): ?>
					<?php foreach ($postsRecent as $post): ?>
						<a class="list-post-tabs" href="<?php echo $block->getUrlByPost($post) ?>">
							<div class="post-left">
								<img class="img-responsive" src="<?php echo $block->getImageUrl($post->getImage())?>">
							</div>
							<div class="post-right">
								<span><?php echo $post->getName() ?></span>
								<span class="create-at">
									<?php echo $post->getFormatCreatedAt(); ?>
								</span>
							</div>
						</a>
	
					<?php endforeach; ?>
	
				<?php else: ?>
					<?php echo __('<div style="'.'height: 50px;line-height: 50px;text-align: center;'.'">No Posts</div>') ?>
				<?php endif; ?>
			</div>
		</div>
</div>