<?php
$posts = $block->getMosviewPosts();
$limit = $block->getLimitPost();
$count = 0;
?>
	<div class="block-title">
			<p class="block-mp-sidebar-heading" role="heading" aria-level="2"><?php echo __('Most Views') ?></p>

	</div>
	<?php if ($posts->getSize()): ?>
		<ul>

<?php foreach ($posts as $post): ?>
	<?php
	$count++;
	if ($count > $limit)
		break;
	?>
	<li>
		<a href="<?php echo $block->getUrlByPost($post) ?>"><?php echo $post->getName() ?>
		</a>
	</li>

<?php endforeach; ?>
</ul>
	<?php else: ?>
		<?php echo __('No Posts') ?>
	<?php endif; ?>