<ul class="mageplaza-head" style="position: static">
    <li><a href="https://docs.mageplaza.com/blog-m2/" target="_blank">User Guide</a> <br>    </li>
    <li><a href="https://mageplaza.freshdesk.com/support/discussions/topics/new?forum_id=6000241371" target="_blank">Report a problem</a> <br></li>
    <li>Your default blog URL <strong>domain.com/blog/</strong> <br></li>
    <li>Atom Feed <strong>domain.com/blog/post/rss/</strong> <br>    </li>
    <li>Sitemap <strong>domain.com/sitemap/blog.xml</strong> <br>    </li>
    <li><strong><a href="https://www.mageplaza.com/" target="_blank">Find more extensions</a></strong> <br></li>

</ul>