
<?php
$posts=$block->getPostList();

?>
	<?php $checkRss = $block->checkRss();
if ($checkRss):
	?>
	<div class="mp-blog-rss">
            <a href="<?php echo $checkRss ?>" class="bb-rss-icon"><img src="<?php echo $this->getViewFileUrl('Mageplaza_Blog::media/images/rss.png') ?>" width="16px"> </a>
        </div>
<?php endif; ?>
<?php if ($posts->getSize() > 0) : ?>
	<?php echo $this->getPagerHtml(); ?>
	<div class="post-list-container mpcss">
		<div class="row">
			<?php foreach ($posts as $post) : ?>
				<div class="post-list-item <?php if($block->getBlogConfig('general/display_style') == 2){echo ' col-sm-6';}else echo ' col-sm-12';?>">
					<div class="post-item-wraper">
						<div class="post-image">
							<?php if ($post->getImage()) : ?>
								<a href="<?php echo $block->getUrlByPost($post) ?>">
									<img class="img-responsive"
										 src="<?php echo $block->getImageUrl($post->getImage()); ?>"
										 alt="<?php echo $block->escapeHtml($post->getName()); ?>"/>
								</a>
							<?php endif; ?>
						</div>
						<div class="post-info-wraper">
							<h2 class="mp-post-title">
								<a class="post-link-title" title="<?php echo $post->getName(); ?>" href="<?php echo $block->getUrlByPost($post) ?>">
									<?php echo $post->getName();?>
								</a>
							</h2>


							<div class="mp-post-info">
								<?php echo __('Posted on'); ?> <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
								$object = $objectManager->get('\Magento\Framework\Stdlib\DateTime\DateTime');
								$dateFormat = date('Y-m-d',$object->timestamp($post->getCreatedAt()));
								echo $dateFormat;
								?> |
								<?php echo __('Posted in'); ?> <?php echo $block->getPostCategoryHtml($post); ?>
							</div>


							<div class="post-short-description">
								<p><?php echo $post->getShortDescription(); ?></p>
							</div>

							<div class="mp-clearfix"></div>


							<div class="mp-post-meta-info mp-alignright">
									<div class="actions">
										<a class="mp-read-more" href="<?php echo $block->getUrlByPost($post); ?>"
										   title="<?php echo __('Read More'); ?>"><?php echo __('Read More'); ?></a>
									</div>
							</div>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
    </div>
		<?php echo $this->getPagerHtml(); ?>
<?php else : ?>
	<div class="post-list-container">
        <?php echo __('There are no posts at this moment'); ?>
    </div>
<?php endif; ?>