<?php
$tags = $block->getTagList();
$limit = 5;
$count = 0;
?>
<div class="mp-sidebar mpcss">
	<div class="row">
		<div class="block-title col-xs-12 sidebar-tags">
				<p class="block-mp-sidebar-heading" role="heading" aria-level="2"><?php echo __('Tags') ?></p>

		</div>
		<div class="col-xs-12">
			<?php if (count($tags) > 0): ?>
				<?php foreach ($tags as $tag): ?>
					<?php
					$count++;
					if ($count > $limit)
						break;
					?>
					<a class="label label-default tags-list" href="<?php echo $block->getTagUrl($tag) ?>"><?php echo $tag->getName(); ?></a>
				<?php endforeach; ?>
				
				<?php else: ?>
					<?php echo __('No Tags') ?>
				<?php endif; ?>
				<hr/>
		</div>
		</div>
</div>