<?php $_post = $block->getCurrentPost();

?>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-568cdc40e9eab41d"
		async="async"></script>

	<div class="page-title post-title">
        <h1><?php echo $_post->getName(); ?></h1>
    </div>
	<div class="post-view">

        <div class="mp-post-info">
            <?php echo __('Posted on'); ?> <?php echo $_post->getCreatedAt() ?>
			|
			<?php echo __('Posted in'); ?> <?php echo $block->getPostCategoryHtml($_post); ?> |
        </div>

        <br>

        <div class="post-image">
           <?php if ($_post->getImage()) : ?>
			   <a href="<?php echo $block->getUrlByPost($_post) ?>">
                            <img
								src="<?php echo $block->getImageUrl($_post->getImage()); ?>"
								alt="<?php echo $block->escapeHtml($_post->getName()); ?>"/>
                        </a>
		   <?php endif; ?>
        </div>


        <div class="post-post_content">
            <?php echo $_post->getPostContent(); ?>
        </div>

    </div>


	<div class="post-sharing-button">
        <div class="addthis_sharing_toolbox"></div>
    </div>
    <div class="post-same-topics post-list">
        <?php $topicCollection = $_post->getSelectedTopicsCollection(); ?>
		<?php if ($topicCollection): ?>
			<h2><?php echo __('Topic'); ?></h2>
			<ul>
                <?php foreach ($topicCollection as $topic): ?>
					<li>
                        <a href="<?php echo $block->getTopicUrl($topic) ?>"><?php echo $topic->getName(); ?></a>
                    </li>
				<?php endforeach; ?>

            </ul>

		<?php endif; ?>

    </div>

	<div class="mp-comment">
			<?php $typeComment = $block->checkComment(); ?>
			<?php if($typeComment== Mageplaza\Blog\Model\Config\Source\Comments\Type::DISQUS): ?>
			<?php elseif ($typeComment== Mageplaza\Blog\Model\Config\Source\Comments\Type::FACEBOOK): ?>

				<div class="box-collateral box-reviews" id="post-reviews">
        <h2><?php echo __('Comments') ?></h2>

        <div id="fb-root"></div>
        <script>(function(d, s, id) {
				var js, fjs = d.getElementsByTagName(s)[0];
				if (d.getElementById(id)) return;
				js = d.createElement(s); js.id = id;
				js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.5&appId=<?php echo $this->getAppId()?>";
				fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script>


        <div class="fb-comments" data-href="<?php echo $_post->getPostUrl();?>" data-numposts="<?php echo $this->getNumberOfComments();?>"
			 data-width="100%" data-colorscheme="<?php echo $this->getColor()?>" ddata-order-by="<?php echo $this->getOrderBy()?>"></div>

    </div>

			<?php endif; ?>
	</div>
